// <auto-generated />
using CleanArch.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CleanArch.Infra.Data.Migrations
{
    [DbContext(typeof(MuseumDbContext))]
    [Migration("20210421220604_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CleanArch.Domain.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artworks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Leonardo Da Vinci",
                            Name = "Mona Lisa",
                            Year = "1503"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Johannes Vermeer",
                            Name = "Girl with a Pealr Earring",
                            Year = "1665"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Michelangelo",
                            Name = "David",
                            Year = "1501"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Banksy",
                            Name = "Love is in the Bin",
                            Year = "2006"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Vincent van Gogh",
                            Name = "The Starry Night",
                            Year = "1889"
                        },
                        new
                        {
                            Id = 6,
                            Artist = "Auguste Rodin",
                            Name = "The Thinker",
                            Year = "1880"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
